export interface Achievement {
    id: string;
    title: string;
    description: string;
    category: "time" | "marathon" | "schedule" | "afk" | "solo" | "duo" | "special";
    difficulty: "Bronze" | "Argent" | "Or" | "Platine";
    check: (stats: {
        totalActiveSec: number;
        sessionsCount: number;
        maxSessionActiveSec: number;
        sessionActiveSec: number;
        sessionDeafSec: number;
        joinHour: number;
        isSolo: boolean;
        targetRank: number;
        activeDayOfWeek: number;
        totalSessionsLength: number;
        userOverlapCount: number;
    }) => boolean;
}

export const ACHIEVEMENTS: Achievement[] = [
    {
        id: "time_1",
        title: "Premier pas",
        description: "Cumuler 2 heures en vocal",
        category: "time",
        difficulty: "Bronze",
        check: (s) => s.totalActiveSec >= 2 * 3600,
    },
    {
        id: "time_2",
        title: "Habitué",
        description: "Cumuler 15 heures en vocal",
        category: "time",
        difficulty: "Bronze",
        check: (s) => s.totalActiveSec >= 15 * 3600,
    },
    {
        id: "time_3",
        title: "Bavard officiel",
        description: "Cumuler 70 heures en vocal",
        category: "time",
        difficulty: "Argent",
        check: (s) => s.totalActiveSec >= 70 * 3600,
    },
    {
        id: "time_4",
        title: "Pilier du serveur",
        description: "Cumuler 200 heures en vocal",
        category: "time",
        difficulty: "Argent",
        check: (s) => s.totalActiveSec >= 200 * 3600,
    },
    {
        id: "time_5",
        title: "Monstre d'endurance",
        description: "Cumuler 650 heures en vocal",
        category: "time",
        difficulty: "Or",
        check: (s) => s.totalActiveSec >= 650 * 3600,
    },
    {
        id: "time_6",
        title: "Divinité vocale",
        description: "Cumuler 1250 heures en vocal",
        category: "time",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 1250 * 3600,
    },
    {
        id: "marathon_1",
        title: "Petite sieste",
        description: "Faire une session active ininterrompue de 3 heures",
        category: "marathon",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec >= 3 * 3600,
    },
    {
        id: "marathon_2",
        title: "Pas là pour rigoler",
        description: "Faire une session active ininterrompue de 5 heures",
        category: "marathon",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec >= 5 * 3600,
    },
    {
        id: "marathon_3",
        title: "La demi-journée",
        description: "Faire une session active ininterrompue de 8 heures",
        category: "marathon",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec >= 8 * 3600,
    },
    {
        id: "marathon_4",
        title: "Le survivant",
        description: "Faire une session active ininterrompue de 12 heures",
        category: "marathon",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec >= 12 * 3600,
    },
    {
        id: "marathon_5",
        title: "Le cycle circadien",
        description: "Faire une session active ininterrompue de 20 heures",
        category: "marathon",
        difficulty: "Or",
        check: (s) => s.sessionActiveSec >= 20 * 3600,
    },
    {
        id: "marathon_6",
        title: "Insomnie médicale",
        description: "Faire une session active ininterrompue de 30 heures",
        category: "marathon",
        difficulty: "Platine",
        check: (s) => s.sessionActiveSec >= 30 * 3600,
    },
    {
        id: "schedule_1",
        title: "Oiseau de nuit",
        description: "Rejoindre le vocal entre 02h et 04h du matin",
        category: "schedule",
        difficulty: "Bronze",
        check: (s) => s.joinHour >= 2 && s.joinHour <= 4,
    },
    {
        id: "schedule_2",
        title: "Le boulanger",
        description: "Rejoindre le vocal entre 05h et 06h du matin",
        category: "schedule",
        difficulty: "Bronze",
        check: (s) => s.joinHour >= 5 && s.joinHour <= 6,
    },
    {
        id: "schedule_3",
        title: "Fidèle au poste",
        description: "Faire une session un samedi ou un dimanche",
        category: "schedule",
        difficulty: "Bronze",
        check: (s) => s.activeDayOfWeek === 0 || s.activeDayOfWeek === 6,
    },
    {
        id: "afk_1",
        title: "Spectateur",
        description: "Passer 45 minutes en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Bronze",
        check: (s) => s.sessionDeafSec >= 45 * 60,
    },
    {
        id: "afk_2",
        title: "Le fantôme",
        description: "Passer 3 heures en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Argent",
        check: (s) => s.sessionDeafSec >= 3 * 3600,
    },
    {
        id: "afk_3",
        title: "Statue de pierre",
        description: "Passer 6 heures en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Or",
        check: (s) => s.sessionDeafSec >= 6 * 3600,
    },
    {
        id: "afk_4",
        title: "Vide intersidéral",
        description: "Passer 12 heures en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Platine",
        check: (s) => s.sessionDeafSec >= 12 * 3600,
    },
    {
        id: "solo_1",
        title: "Tranquillité",
        description: "Passer 2 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Bronze",
        check: (s) => s.isSolo && s.sessionActiveSec >= 2 * 3600,
    },
    {
        id: "solo_2",
        title: "Sermon solitaire",
        description: "Passer 5 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Bronze",
        check: (s) => s.isSolo && s.sessionActiveSec >= 5 * 3600,
    },
    {
        id: "solo_3",
        title: "Castaway",
        description: "Passer 10 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Argent",
        check: (s) => s.isSolo && s.sessionActiveSec >= 10 * 3600,
    },
    {
        id: "solo_4",
        title: "Le gardien du phare",
        description: "Passer 18 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Or",
        check: (s) => s.isSolo && s.sessionActiveSec >= 18 * 3600,
    },
    {
        id: "solo_5",
        title: "Espace infini",
        description: "Passer 30 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Platine",
        check: (s) => s.isSolo && s.sessionActiveSec >= 30 * 3600,
    },
    {
        id: "duo_1",
        title: "Duo dynamique",
        description: "Partager une session en tête à tête avec une personne pendant au moins 2 heures",
        category: "duo",
        difficulty: "Bronze",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 2 * 3600,
    },
    {
        id: "duo_2",
        title: "Confidents",
        description: "Partager une session en tête à tête avec une personne pendant au moins 4 heures",
        category: "duo",
        difficulty: "Argent",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 4 * 3600,
    },
    {
        id: "duo_3",
        title: "Frères d'armes",
        description: "Partager une session en tête à tête avec une personne pendant au moins 8 heures",
        category: "duo",
        difficulty: "Or",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 8 * 3600,
    },
    {
        id: "duo_4",
        title: "Âmes sœurs",
        description: "Partager une session en tête à tête avec une personne pendant au moins 15 heures",
        category: "duo",
        difficulty: "Platine",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 15 * 3600,
    },
    {
        id: "special_1",
        title: "Le curieux",
        description: "Cumuler 75 sessions vocales distinctes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionsCount >= 75,
    },
    {
        id: "special_2",
        title: "Le squatteur",
        description: "Cumuler 250 sessions vocales distinctes",
        category: "special",
        difficulty: "Argent",
        check: (s) => s.sessionsCount >= 250,
    },
    {
        id: "special_3",
        title: "L'ancien du village",
        description: "Cumuler 1200 sessions vocales distinctes",
        category: "special",
        difficulty: "Or",
        check: (s) => s.sessionsCount >= 1200,
    },
    {
        id: "special_4",
        title: "Haut du panier",
        description: "Faire partie du Top 3 au classement général",
        category: "special",
        difficulty: "Or",
        check: (s) => s.targetRank <= 3 && s.targetRank > 0,
    },
    {
        id: "special_5",
        title: "Le roi du vocal",
        description: "S'emparer du Rang 1 au classement général",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.targetRank === 1,
    },
    {
        id: "special_6",
        title: "La session éclair",
        description: "Faire une session active qui dure précisément entre 1 et 10 secondes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec >= 1 && s.sessionActiveSec <= 10,
    },
    {
        id: "special_7",
        title: "Pas le temps",
        description: "Faire une session active de moins de 5 secondes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec > 0 && s.sessionActiveSec < 5,
    },
    {
        id: "special_8",
        title: "Accro au clic",
        description: "Cumuler 3000 sessions vocales distinctes",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.sessionsCount >= 3000,
    },
    {
        id: "special_9",
        title: "Parfaitement équilibré",
        description: "Faire une session active qui dure exactement 1 heure",
        category: "special",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec === 3600,
    },
    {
        id: "special_10",
        title: "Seconde exacte",
        description: "Faire une session active qui dure exactement 42 secondes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec === 42,
    },
    {
        id: "special_11",
        title: "Couche-tard",
        description: "Faire une session active de plus de 5 heures débutée après 22h et terminée avant 04h",
        category: "special",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec >= 5 * 3600 && (s.joinHour >= 22 || s.joinHour < 4),
    },
    {
        id: "special_12",
        title: "Grand voyageur",
        description: "Cumuler au moins 1800 heures en vocal",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 1800 * 3600,
    },
    {
        id: "special_13",
        title: "La folie du chiffre",
        description: "Cumuler exactement 777 heures de présence active en vocal",
        category: "special",
        difficulty: "Or",
        check: (s) => Math.floor(s.totalActiveSec / 3600) === 777,
    },
    {
        id: "special_14",
        title: "L'ombre des salons",
        description: "Faire une session active de plus de 10 heures qui s'est déroulée entièrement seul",
        category: "special",
        difficulty: "Or",
        check: (s) => s.isSolo && s.sessionActiveSec >= 10 * 3600,
    },
    {
        id: "special_15",
        title: "Le marathonien de l'extrême",
        description: "Faire une session active de plus de 25 heures",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.sessionActiveSec >= 25 * 3600,
    },
    {
        id: "special_16",
        title: "Sprint matinal",
        description: "Faire une session de moins de 10 minutes débutée précisément à 06h00",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.joinHour === 6 && s.sessionActiveSec > 0 && s.sessionActiveSec < 600,
    },
    {
        id: "special_17",
        title: "Faux départ",
        description: "Faire 3 sessions de moins de 10 secondes au cours de la même journée",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec > 0 && s.sessionActiveSec < 10,
    },
    {
        id: "special_18",
        title: "Membre de Bronze",
        description: "Entrer dans le Top 10 au classement général",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.targetRank <= 10 && s.targetRank > 0,
    },
    {
        id: "special_19",
        title: "Podium virtuel",
        description: "Faire partie du Top 3 au classement général",
        category: "special",
        difficulty: "Or",
        check: (s) => s.targetRank <= 3 && s.targetRank > 0,
    },
    {
        id: "special_20",
        title: "Le bavard éternel",
        description: "Cumuler 2200 heures en vocal",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 2200 * 3600,
    },
    {
        id: "special_21",
        title: "Exactitude",
        description: "Faire une session active qui dure exactement 12 heures",
        category: "special",
        difficulty: "Or",
        check: (s) => s.sessionActiveSec === 12 * 3600,
    },
    {
        id: "special_22",
        title: "Bavard infini",
        description: "Cumuler 3500 heures en vocal",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 3500 * 3600,
    }
];
