export interface Achievement {
    id: string;
    title: string;
    description: string;
    category: "time" | "marathon" | "schedule" | "afk" | "solo" | "duo" | "special" | "skill";
    difficulty: "Bronze" | "Argent" | "Or" | "Platine";
    check: (stats: {
        totalActiveSec: number;
        sessionsCount: number;
        maxSessionActiveSec: number;
        sessionActiveSec: number;
        sessionDeafSec: number;
        joinHour: number;
        isSolo: boolean;
        targetRank: number;
        activeDayOfWeek: number;
        totalSessionsLength: number;
        userOverlapCount: number;
    }) => boolean;
}

export const ACHIEVEMENTS: Achievement[] = [
    {
        id: "time_1",
        title: "Premier pas",
        description: "Cumuler 10 heures en vocal",
        category: "time",
        difficulty: "Bronze",
        check: (s) => s.totalActiveSec >= 10 * 3600,
    },
    {
        id: "time_2",
        title: "Habitué",
        description: "Cumuler 50 heures en vocal",
        category: "time",
        difficulty: "Bronze",
        check: (s) => s.totalActiveSec >= 50 * 3600,
    },
    {
        id: "time_3",
        title: "Bavard officiel",
        description: "Cumuler 200 heures en vocal",
        category: "time",
        difficulty: "Argent",
        check: (s) => s.totalActiveSec >= 200 * 3600,
    },
    {
        id: "time_4",
        title: "Pilier du serveur",
        description: "Cumuler 500 heures en vocal",
        category: "time",
        difficulty: "Argent",
        check: (s) => s.totalActiveSec >= 500 * 3600,
    },
    {
        id: "time_5",
        title: "Monstre d'endurance",
        description: "Cumuler 1000 heures en vocal",
        category: "time",
        difficulty: "Or",
        check: (s) => s.totalActiveSec >= 1000 * 3600,
    },
    {
        id: "time_6",
        title: "Divinité vocale",
        description: "Cumuler 2000 heures en vocal",
        category: "time",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 2000 * 3600,
    },
    {
        id: "marathon_1",
        title: "Petite sieste",
        description: "Faire une session active ininterrompue de 5 heures",
        category: "marathon",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec >= 5 * 3600,
    },
    {
        id: "marathon_2",
        title: "Pas là pour rigoler",
        description: "Faire une session active ininterrompue de 8 heures",
        category: "marathon",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec >= 8 * 3600,
    },
    {
        id: "marathon_3",
        title: "La demi-journée",
        description: "Faire une session active ininterrompue de 12 heures",
        category: "marathon",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec >= 12 * 3600,
    },
    {
        id: "marathon_4",
        title: "Le survivant",
        description: "Faire une session active ininterrompue de 18 heures",
        category: "marathon",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec >= 18 * 3600,
    },
    {
        id: "marathon_5",
        title: "Le cycle circadien",
        description: "Faire une session active ininterrompue de 25 heures",
        category: "marathon",
        difficulty: "Or",
        check: (s) => s.sessionActiveSec >= 25 * 3600,
    },
    {
        id: "marathon_6",
        title: "Insomnie médicale",
        description: "Faire une session active ininterrompue de 36 heures",
        category: "marathon",
        difficulty: "Platine",
        check: (s) => s.sessionActiveSec >= 36 * 3600,
    },
    {
        id: "schedule_1",
        title: "Oiseau de nuit",
        description: "Rejoindre le vocal entre 02h et 04h du matin",
        category: "schedule",
        difficulty: "Bronze",
        check: (s) => s.joinHour >= 2 && s.joinHour <= 4,
    },
    {
        id: "schedule_2",
        title: "Le boulanger",
        description: "Rejoindre le vocal entre 05h et 06h du matin",
        category: "schedule",
        difficulty: "Bronze",
        check: (s) => s.joinHour >= 5 && s.joinHour <= 6,
    },
    {
        id: "schedule_3",
        title: "Fidèle au poste",
        description: "Faire une session un samedi ou un dimanche",
        category: "schedule",
        difficulty: "Bronze",
        check: (s) => s.activeDayOfWeek === 0 || s.activeDayOfWeek === 6,
    },
    {
        id: "afk_1",
        title: "Spectateur",
        description: "Passer 2 heures en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Bronze",
        check: (s) => s.sessionDeafSec >= 2 * 3600,
    },
    {
        id: "afk_2",
        title: "Le fantôme",
        description: "Passer 5 heures en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Argent",
        check: (s) => s.sessionDeafSec >= 5 * 3600,
    },
    {
        id: "afk_3",
        title: "Statue de pierre",
        description: "Passer 8 heures en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Or",
        check: (s) => s.sessionDeafSec >= 8 * 3600,
    },
    {
        id: "afk_4",
        title: "Vide intersidéral",
        description: "Passer 15 heures en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Platine",
        check: (s) => s.sessionDeafSec >= 15 * 3600,
    },
    {
        id: "solo_1",
        title: "Tranquillité",
        description: "Passer 4 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Bronze",
        check: (s) => s.isSolo && s.sessionActiveSec >= 4 * 3600,
    },
    {
        id: "solo_2",
        title: "Sermon solitaire",
        description: "Passer 8 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Bronze",
        check: (s) => s.isSolo && s.sessionActiveSec >= 8 * 3600,
    },
    {
        id: "solo_3",
        title: "Castaway",
        description: "Passer 15 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Argent",
        check: (s) => s.isSolo && s.sessionActiveSec >= 15 * 3600,
    },
    {
        id: "solo_4",
        title: "Le gardien du phare",
        description: "Passer 24 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Or",
        check: (s) => s.isSolo && s.sessionActiveSec >= 24 * 3600,
    },
    {
        id: "solo_5",
        title: "Espace infini",
        description: "Passer 36 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Platine",
        check: (s) => s.isSolo && s.sessionActiveSec >= 36 * 3600,
    },
    {
        id: "duo_1",
        title: "Duo dynamique",
        description: "Partager une session en tête à tête avec une personne pendant au moins 4 heures",
        category: "duo",
        difficulty: "Bronze",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 4 * 3600,
    },
    {
        id: "duo_2",
        title: "Confidents",
        description: "Partager une session en tête à tête avec une personne pendant au moins 8 heures",
        category: "duo",
        difficulty: "Argent",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 8 * 3600,
    },
    {
        id: "duo_3",
        title: "Frères d'armes",
        description: "Partager une session en tête à tête avec une personne pendant au moins 15 heures",
        category: "duo",
        difficulty: "Or",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 15 * 3600,
    },
    {
        id: "duo_4",
        title: "Âmes sœurs",
        description: "Partager une session en tête à tête avec une personne pendant au moins 24 heures",
        category: "duo",
        difficulty: "Platine",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 24 * 3600,
    },
    {
        id: "special_1",
        title: "Le curieux",
        description: "Cumuler 150 sessions vocales distinctes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionsCount >= 150,
    },
    {
        id: "special_2",
        title: "Le squatteur",
        description: "Cumuler 500 sessions vocales distinctes",
        category: "special",
        difficulty: "Argent",
        check: (s) => s.sessionsCount >= 500,
    },
    {
        id: "special_3",
        title: "L'ancien du village",
        description: "Cumuler 1500 sessions vocales distinctes",
        category: "special",
        difficulty: "Or",
        check: (s) => s.sessionsCount >= 1500,
    },
    {
        id: "special_4",
        title: "Haut du panier",
        description: "Faire partie du Top 3 au classement général",
        category: "special",
        difficulty: "Or",
        check: (s) => s.targetRank <= 3 && s.targetRank > 0,
    },
    {
        id: "special_5",
        title: "Le roi du vocal",
        description: "S'emparer du Rang 1 au classement général",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.targetRank === 1,
    },
    {
        id: "special_6",
        title: "La session éclair",
        description: "Faire une session active qui dure précisément entre 1 et 10 secondes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec >= 1 && s.sessionActiveSec <= 10,
    },
    {
        id: "special_7",
        title: "Pas le temps",
        description: "Faire une session active de moins de 5 secondes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec > 0 && s.sessionActiveSec < 5,
    },
    {
        id: "special_8",
        title: "Accro au clic",
        description: "Cumuler 4000 sessions vocales distinctes",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.sessionsCount >= 4000,
    },
    {
        id: "special_9",
        title: "Parfaitement équilibré",
        description: "Faire une session active qui dure exactement 1 heure",
        category: "special",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec === 3600,
    },
    {
        id: "special_10",
        title: "Seconde exacte",
        description: "Faire une session active qui dure exactement 42 secondes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec === 42,
    },
    {
        id: "special_11",
        title: "Couche-tard",
        description: "Faire une session active de plus de 5 heures débutée après 22h et terminée avant 04h",
        category: "special",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec >= 5 * 3600 && (s.joinHour >= 22 || s.joinHour < 4),
    },
    {
        id: "special_12",
        title: "Grand voyageur",
        description: "Cumuler au moins 2500 heures en vocal",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 2500 * 3600,
    },
    {
        id: "special_13",
        title: "La folie du chiffre",
        description: "Cumuler exactement 777 heures de présence active en vocal",
        category: "special",
        difficulty: "Or",
        check: (s) => Math.floor(s.totalActiveSec / 3600) === 777,
    },
    {
        id: "special_14",
        title: "L'ombre des salons",
        description: "Faire une session active de plus de 15 heures qui s'est déroulée entièrement seul",
        category: "special",
        difficulty: "Or",
        check: (s) => s.isSolo && s.sessionActiveSec >= 15 * 3600,
    },
    {
        id: "special_15",
        title: "Le marathonien de l'extrême",
        description: "Faire une session active de plus de 36 heures",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.sessionActiveSec >= 36 * 3600,
    },
    {
        id: "special_16",
        title: "Sprint matinal",
        description: "Faire une session de moins de 10 minutes débutée précisément à 06h00",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.joinHour === 6 && s.sessionActiveSec > 0 && s.sessionActiveSec < 600,
    },
    {
        id: "special_17",
        title: "Faux départ",
        description: "Faire 3 sessions de moins de 10 secondes au cours de la même journée",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec > 0 && s.sessionActiveSec < 10,
    },
    {
        id: "special_18",
        title: "Membre de Bronze",
        description: "Entrer dans le Top 10 au classement général",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.targetRank <= 10 && s.targetRank > 0,
    },
    {
        id: "special_19",
        title: "Podium virtuel",
        description: "Faire partie du Top 3 au classement général",
        category: "special",
        difficulty: "Or",
        check: (s) => s.targetRank <= 3 && s.targetRank > 0,
    },
    {
        id: "special_20",
        title: "Le bavard éternel",
        description: "Cumuler 3000 heures en vocal",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 3000 * 3600,
    },
    {
        id: "special_21",
        title: "Exactitude",
        description: "Faire une session active qui dure exactement 18 heures",
        category: "special",
        difficulty: "Or",
        check: (s) => s.sessionActiveSec === 18 * 3600,
    },
    {
        id: "special_22",
        title: "Bavard infini",
        description: "Cumuler 4000 heures en vocal",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 4000 * 3600,
    },
    {
        id: "skill_1",
        title: "La seconde parfaite",
        description: "Faire une session active qui dure exactement 60 secondes",
        category: "skill",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec === 60,
    },
    {
        id: "skill_2",
        title: "Le double pile",
        description: "Faire deux sessions actives consécutives de minutes piles (ignore en historique, verifie par session)",
        category: "skill",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec > 0 && s.sessionActiveSec % 60 === 0,
    },
    {
        id: "skill_3",
        title: "Le pile ou face",
        description: "Faire une session dont la durée totale en secondes est un palindrome (ex: 121s)",
        category: "skill",
        difficulty: "Bronze",
        check: (s) => {
            const str = s.sessionActiveSec.toString();
            return str.length >= 3 && str === str.split("").reverse().join("");
        },
    },
    {
        id: "skill_4",
        title: "La minute d'or",
        description: "Passer exactement 60 secondes en sourdine sur une session de 10 minutes",
        category: "skill",
        difficulty: "Argent",
        check: (s) => s.sessionDeafSec === 60 && s.sessionActiveSec + s.sessionDeafSec === 600,
    },
    {
        id: "skill_5",
        title: "Le micro-départ",
        description: "Se connecter, rester actif exactement 3 secondes, et quitter",
        category: "skill",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec === 3,
    },
    {
        id: "skill_6",
        title: "Le compte à rebours",
        description: "Faire une session active de 10 minutes et 9 secondes",
        category: "skill",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec === 609,
    },
    {
        id: "skill_7",
        title: "La pause réglementaire",
        description: "Rester connecté pendant 15 minutes, avec précisément 3 minutes de sourdine",
        category: "skill",
        difficulty: "Argent",
        check: (s) => s.sessionDeafSec === 180 && s.sessionActiveSec + s.sessionDeafSec === 900,
    },
    {
        id: "skill_8",
        title: "Le métronome",
        description: "Faire une session avec un ratio parfait d'intervalles",
        category: "skill",
        difficulty: "Or",
        check: (s) => s.sessionDeafSec > 0 && s.sessionActiveSec % 300 === 0 && s.sessionDeafSec % 60 === 0,
    },
    {
        id: "skill_9",
        title: "Le fantôme actif",
        description: "Faire une session de 30 minutes avec exactement 50% de temps en sourdine",
        category: "skill",
        difficulty: "Or",
        check: (s) => s.sessionActiveSec + s.sessionDeafSec === 1800 && s.sessionActiveSec === s.sessionDeafSec,
    },
    {
        id: "skill_10",
        title: "L'éclair silencieux",
        description: "Rester sourdine casque exactement 42 secondes et quitter sans s'activer",
        category: "skill",
        difficulty: "Bronze",
        check: (s) => s.sessionDeafSec === 42 && s.sessionActiveSec === 0,
    },
    {
        id: "skill_11",
        title: "Sourdine chirurgicale",
        description: "Faire une session d'une heure ou plus avec exactement 10 secondes de sourdine",
        category: "skill",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec >= 3600 && s.sessionDeafSec === 10,
    },
    {
        id: "skill_12",
        title: "Le switch rapide",
        description: "Faire une session avec précisément 5 bascules rapides",
        category: "skill",
        difficulty: "Bronze",
        check: (s) => s.sessionDeafSec > 0 && s.sessionActiveSec > 0 && (s.sessionDeafSec + s.sessionActiveSec < 30),
    },
    {
        id: "skill_13",
        title: "L'esquive de record",
        description: "Terminer une session active à moins de 5 secondes de battre son propre record",
        category: "skill",
        difficulty: "Argent",
        check: (s) => s.maxSessionActiveSec > 0 && s.sessionActiveSec < s.maxSessionActiveSec && s.maxSessionActiveSec - s.sessionActiveSec <= 5,
    },
    {
        id: "skill_14",
        title: "Le synchronisé",
        description: "Se connecter en même temps qu'un autre membre",
        category: "skill",
        difficulty: "Bronze",
        check: (s) => s.userOverlapCount >= 1 && !s.isSolo && s.sessionActiveSec > 0,
    },
    {
        id: "skill_15",
        title: "Le croisement",
        description: "Changement de garde immédiat avec un membre",
        category: "skill",
        difficulty: "Bronze",
        check: (s) => s.userOverlapCount >= 1 && s.sessionActiveSec > 0,
    },
    {
        id: "skill_16",
        title: "L'alignement des planètes",
        description: "Rejoindre le vocal exactement à une heure pile (à la seconde près)",
        category: "skill",
        difficulty: "Argent",
        check: () => {
            const joinDate = new Date(); 
            return joinDate.getMinutes() === 0 && joinDate.getSeconds() === 0;
        },
    },
    {
        id: "skill_17",
        title: "Le saut de puce",
        description: "Changer de salon vocal en moins de 2 secondes",
        category: "skill",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec > 0 && s.sessionActiveSec < 2,
    },
    {
        id: "skill_18",
        title: "L'ombre instantanée",
        description: "Suivre la déconnexion d'un membre en moins de 5 secondes",
        category: "skill",
        difficulty: "Bronze",
        check: (s) => s.userOverlapCount >= 1 && s.sessionActiveSec > 0 && s.sessionActiveSec <= 5,
    },
    {
        id: "skill_19",
        title: "Le ninja",
        description: "Faire une session active de 5 minutes seul du début à la fin",
        category: "skill",
        difficulty: "Bronze",
        check: (s) => s.isSolo && s.sessionActiveSec === 300,
    },
    {
        id: "skill_20",
        title: "Le tampon",
        description: "Lancer une discussion à trois puis s'éclipser au bout d'une minute",
        category: "skill",
        difficulty: "Argent",
        check: (s) => s.userOverlapCount === 2 && s.sessionActiveSec <= 65 && s.sessionActiveSec >= 55,
    },
    {
        id: "skill_21",
        title: "Le chef d'orchestre",
        description: "Réunir 5 personnes dans un salon et partir ensemble",
        category: "skill",
        difficulty: "Or",
        check: (s) => s.userOverlapCount >= 4 && s.sessionActiveSec > 0,
    },
    {
        id: "skill_22",
        title: "L'infiltré",
        description: "Rejoindre 3 personnes, rester exactement 1 minute actif et repartir",
        category: "skill",
        difficulty: "Bronze",
        check: (s) => s.userOverlapCount === 3 && s.sessionActiveSec === 60,
    },
    {
        id: "skill_23",
        title: "La garde alternée",
        description: "Changer de partenaire de duo régulièrement au cours de la session",
        category: "skill",
        difficulty: "Or",
        check: (s) => s.userOverlapCount >= 3 && s.sessionActiveSec >= 7200,
    },
    {
        id: "skill_24",
        title: "Le relais",
        description: "Rester connecté pendant que 4 membres différents se succèdent",
        category: "skill",
        difficulty: "Or",
        check: (s) => s.userOverlapCount >= 4 && s.sessionActiveSec >= 3600,
    },
    {
        id: "skill_25",
        title: "L'hôte d'un soir",
        description: "Faire en sorte que 3 personnes différentes se succèdent sur votre salon vocal",
        category: "skill",
        difficulty: "Argent",
        check: (s) => s.userOverlapCount >= 3 && s.sessionActiveSec >= 1800,
    }
];
