export interface Achievement {
    id: string;
    title: string;
    description: string;
    category: "time" | "marathon" | "schedule" | "afk" | "solo" | "duo" | "special";
    difficulty: "Bronze" | "Argent" | "Or" | "Platine";
    check: (stats: {
        totalActiveSec: number;
        sessionsCount: number;
        maxSessionActiveSec: number;
        sessionActiveSec: number;
        sessionDeafSec: number;
        joinHour: number;
        isSolo: boolean;
        targetRank: number;
        activeDayOfWeek: number;
        totalSessionsLength: number;
        userOverlapCount: number;
    }) => boolean;
}

export const ACHIEVEMENTS: Achievement[] = [
    {
        id: "time_1",
        title: "Premier pas",
        description: "Cumuler 1 heure en vocal",
        category: "time",
        difficulty: "Bronze",
        check: (s) => s.totalActiveSec >= 3600,
    },
    {
        id: "time_2",
        title: "Habitué",
        description: "Cumuler 10 heures en vocal",
        category: "time",
        difficulty: "Bronze",
        check: (s) => s.totalActiveSec >= 10 * 3600,
    },
    {
        id: "time_3",
        title: "Bavard officiel",
        description: "Cumuler 50 heures en vocal",
        category: "time",
        difficulty: "Argent",
        check: (s) => s.totalActiveSec >= 50 * 3600,
    },
    {
        id: "time_4",
        title: "Pilier du serveur",
        description: "Cumuler 150 heures en vocal",
        category: "time",
        difficulty: "Argent",
        check: (s) => s.totalActiveSec >= 150 * 3600,
    },
    {
        id: "time_5",
        title: "Monstre d'endurance",
        description: "Cumuler 500 heures en vocal",
        category: "time",
        difficulty: "Or",
        check: (s) => s.totalActiveSec >= 500 * 3600,
    },
    {
        id: "time_6",
        title: "Divinité vocale",
        description: "Cumuler 1000 heures en vocal",
        category: "time",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 1000 * 3600,
    },
    {
        id: "marathon_1",
        title: "Petite sieste",
        description: "Faire une session active ininterrompue de 2 heures",
        category: "marathon",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec >= 2 * 3600,
    },
    {
        id: "marathon_2",
        title: "Pas là pour rigoler",
        description: "Faire une session active ininterrompue de 4 heures",
        category: "marathon",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec >= 4 * 3600,
    },
    {
        id: "marathon_3",
        title: "La demi-journée",
        description: "Faire une session active ininterrompue de 6 heures",
        category: "marathon",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec >= 6 * 3600,
    },
    {
        id: "marathon_4",
        title: "Le survivant",
        description: "Faire une session active ininterrompue de 10 heures",
        category: "marathon",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec >= 10 * 3600,
    },
    {
        id: "marathon_5",
        title: "Le cycle circadien",
        description: "Faire une session active ininterrompue de 16 heures",
        category: "marathon",
        difficulty: "Or",
        check: (s) => s.sessionActiveSec >= 16 * 3600,
    },
    {
        id: "marathon_6",
        title: "Insomnie médicale",
        description: "Faire une session active ininterrompue de 24 heures",
        category: "marathon",
        difficulty: "Platine",
        check: (s) => s.sessionActiveSec >= 24 * 3600,
    },
    {
        id: "schedule_1",
        title: "Oiseau de nuit",
        description: "Rejoindre le vocal entre 01h et 04h du matin",
        category: "schedule",
        difficulty: "Bronze",
        check: (s) => s.joinHour >= 1 && s.joinHour <= 4,
    },
    {
        id: "schedule_2",
        title: "Le boulanger",
        description: "Rejoindre le vocal entre 05h et 07h du matin",
        category: "schedule",
        difficulty: "Bronze",
        check: (s) => s.joinHour >= 5 && s.joinHour <= 7,
    },
    {
        id: "schedule_3",
        title: "Fidèle au poste",
        description: "Faire une session un samedi ou un dimanche",
        category: "schedule",
        difficulty: "Bronze",
        check: (s) => s.activeDayOfWeek === 0 || s.activeDayOfWeek === 6,
    },
    {
        id: "afk_1",
        title: "Spectateur",
        description: "Passer 30 minutes en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Bronze",
        check: (s) => s.sessionDeafSec >= 30 * 60,
    },
    {
        id: "afk_2",
        title: "Le fantôme",
        description: "Passer 2 heures en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Argent",
        check: (s) => s.sessionDeafSec >= 2 * 3600,
    },
    {
        id: "afk_3",
        title: "Statue de pierre",
        description: "Passer 5 heures en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Or",
        check: (s) => s.sessionDeafSec >= 5 * 3600,
    },
    {
        id: "afk_4",
        title: "Vide intersidéral",
        description: "Passer 10 heures en sourdine casque sur une seule session",
        category: "afk",
        difficulty: "Platine",
        check: (s) => s.sessionDeafSec >= 10 * 3600,
    },
    {
        id: "solo_1",
        title: "Tranquillité",
        description: "Passer 1 heure seul en salon du début à la fin",
        category: "solo",
        difficulty: "Bronze",
        check: (s) => s.isSolo && s.sessionActiveSec >= 3600,
    },
    {
        id: "solo_2",
        title: "Sermon solitaire",
        description: "Passer 4 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Bronze",
        check: (s) => s.isSolo && s.sessionActiveSec >= 4 * 3600,
    },
    {
        id: "solo_3",
        title: "Castaway",
        description: "Passer 8 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Argent",
        check: (s) => s.isSolo && s.sessionActiveSec >= 8 * 3600,
    },
    {
        id: "solo_4",
        title: "Le gardien du phare",
        description: "Passer 15 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Or",
        check: (s) => s.isSolo && s.sessionActiveSec >= 15 * 3600,
    },
    {
        id: "solo_5",
        title: "Espace infini",
        description: "Passer 24 heures seul en salon du début à la fin",
        category: "solo",
        difficulty: "Platine",
        check: (s) => s.isSolo && s.sessionActiveSec >= 24 * 3600,
    },
    {
        id: "duo_1",
        title: "Duo dynamique",
        description: "Partager une session en tête à tête avec une personne pendant au moins 1 heure",
        category: "duo",
        difficulty: "Bronze",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 3600,
    },
    {
        id: "duo_2",
        title: "Confidents",
        description: "Partager une session en tête à tête avec une personne pendant au moins 3 heures",
        category: "duo",
        difficulty: "Argent",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 3 * 3600,
    },
    {
        id: "duo_3",
        title: "Frères d'armes",
        description: "Partager une session en tête à tête avec une personne pendant au moins 6 heures",
        category: "duo",
        difficulty: "Or",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 6 * 3600,
    },
    {
        id: "duo_4",
        title: "Âmes sœurs",
        description: "Partager une session en tête à tête avec une personne pendant au moins 12 heures",
        category: "duo",
        difficulty: "Platine",
        check: (s) => s.userOverlapCount === 1 && s.sessionActiveSec >= 12 * 3600,
    },
    {
        id: "special_1",
        title: "Le curieux",
        description: "Cumuler 50 sessions vocales distinctes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionsCount >= 50,
    },
    {
        id: "special_2",
        title: "Le squatteur",
        description: "Cumuler 200 sessions vocales distinctes",
        category: "special",
        difficulty: "Argent",
        check: (s) => s.sessionsCount >= 200,
    },
    {
        id: "special_3",
        title: "L'ancien du village",
        description: "Cumuler 1000 sessions vocales distinctes",
        category: "special",
        difficulty: "Or",
        check: (s) => s.sessionsCount >= 1000,
    },
    {
        id: "special_4",
        title: "Haut du panier",
        description: "Faire partie du Top 5 au classement général",
        category: "special",
        difficulty: "Or",
        check: (s) => s.targetRank <= 5 && s.targetRank > 0,
    },
    {
        id: "special_5",
        title: "Le roi du vocal",
        description: "S'emparer du Rang 1 au classement général",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.targetRank === 1,
    },
    {
        id: "special_6",
        title: "La session éclair",
        description: "Faire une session active qui dure précisément entre 1 et 10 secondes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec >= 1 && s.sessionActiveSec <= 10,
    },
    {
        id: "special_7",
        title: "Pas le temps",
        description: "Faire une session active de moins de 5 secondes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec > 0 && s.sessionActiveSec < 5,
    },
    {
        id: "special_8",
        title: "Accro au clic",
        description: "Cumuler 2500 sessions vocales distinctes",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.sessionsCount >= 2500,
    },
    {
        id: "special_9",
        title: "Parfaitement équilibré",
        description: "Faire une session active qui dure exactement 1 heure",
        category: "special",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec === 3600,
    },
    {
        id: "special_10",
        title: "Seconde exacte",
        description: "Faire une session active qui dure exactement 42 secondes",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec === 42,
    },
    {
        id: "special_11",
        title: "Couche-tard",
        description: "Faire une session active de plus de 4 heures débutée après 22h et terminée avant 04h",
        category: "special",
        difficulty: "Argent",
        check: (s) => s.sessionActiveSec >= 4 * 3600 && (s.joinHour >= 22 || s.joinHour < 4),
    },
    {
        id: "special_12",
        title: "Grand voyageur",
        description: "Cumuler au moins 1500 heures en vocal",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 1500 * 3600,
    },
    {
        id: "special_13",
        title: "La folie du chiffre",
        description: "Cumuler exactement 777 heures de présence active en vocal",
        category: "special",
        difficulty: "Or",
        check: (s) => Math.floor(s.totalActiveSec / 3600) === 777,
    },
    {
        id: "special_14",
        title: "L'ombre des salons",
        description: "Faire une session active de plus de 8 heures qui s'est déroulée entièrement seul",
        category: "special",
        difficulty: "Or",
        check: (s) => s.isSolo && s.sessionActiveSec >= 8 * 3600,
    },
    {
        id: "special_15",
        title: "Le marathonien de l'extrême",
        description: "Faire une session active de plus de 20 heures",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.sessionActiveSec >= 20 * 3600,
    },
    {
        id: "special_16",
        title: "Sprint matinal",
        description: "Faire une session de moins de 10 minutes débutée précisément à 06h00",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.joinHour === 6 && s.sessionActiveSec > 0 && s.sessionActiveSec < 600,
    },
    {
        id: "special_17",
        title: "Faux départ",
        description: "Faire 3 sessions de moins de 10 secondes au cours de la même journée",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.sessionActiveSec > 0 && s.sessionActiveSec < 10,
    },
    {
        id: "special_18",
        title: "Membre de Bronze",
        description: "Entrer dans le Top 10 au classement général",
        category: "special",
        difficulty: "Bronze",
        check: (s) => s.targetRank <= 10 && s.targetRank > 0,
    },
    {
        id: "special_19",
        title: "Podium virtuel",
        description: "Faire partie du Top 3 au classement général",
        category: "special",
        difficulty: "Or",
        check: (s) => s.targetRank <= 3 && s.targetRank > 0,
    },
    {
        id: "special_20",
        title: "Le bavard éternel",
        description: "Cumuler 2000 heures en vocal",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 2000 * 3600,
    },
    {
        id: "special_21",
        title: "Exactitude",
        description: "Faire une session active qui dure exactement 10 heures",
        category: "special",
        difficulty: "Or",
        check: (s) => s.sessionActiveSec === 10 * 3600,
    },
    {
        id: "special_22",
        title: "Bavard infini",
        description: "Cumuler 3000 heures en vocal",
        category: "special",
        difficulty: "Platine",
        check: (s) => s.totalActiveSec >= 3000 * 3600,
    }
];
